### ISSUE TITLE
Getting a Check the Log error when trying to open a program marked as (Series)

### ISSUE THREAD

**Issue by missjane63** [ertyertyerty/plugin.video.tvo#9]
Getting a Check the Log error when trying to open a program marked as (Series).  Individual programs open fine, programs that are series get the error

Kodi 20.2/Win 7/TVO ver 5.0.0

**Comment by ertyertyerty** [comment]
Fixed with version 5.0.1
datetime.strptime() returned Null on some platforms some of the time.
Swapped out for time.strptime()
